### ISSUE TITLE
[issue] WPGraphQL_MenuItem / FetchError reason: self signed certificate

### ISSUE THREAD

**Issue by dmhendricks** [zgordon/twentynineteen-gatsby-theme#11]
I'm new to this, but I will post here in case this trips anyone else up. When I ran:

```bash
yarn workspace starter develop
```

I received various errors related to communicating with WPGraphQL:

```
error Plugin gatsby-source-graphql returned an error
	FetchError: request to https://mysite.local/graphql failed, reason: self signed certificate
...
error Plugin gatsby-theme-twentynineteen returned an error
	TypeError: Cannot destructure property `wpgraphql` of 'undefined' or 'null'.
...
error GraphQL Error Unknown type "WPGraphQL_MenuItem".
...
```

As noted by the first error and despite the cert being trusted on my Mac, Node didn't like my self-signed certificate (which was generated via Local by Flywheel), so I had to add this to [packages/gatsby-theme-twentynineteen/gatsby-node.js](https://github.com/zgordon/twentynineteen-gatsby-theme/blob/master/packages/gatsby-theme-twentynineteen/gatsby-node.js):

```js
process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0
```

After that, it compiled fine. 🤘

**Comment by anamwp** [comment]
Adding `process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0` this inside gatsby-node.js of gatsby-twentynineteen folder does not solve my problem. I can not run `yarn workspace starter develop`. 
Can some assist me :) .. I appreciate any help. 
Thanks.

**Comment by phpbits** [comment]
> ```js
> process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0
> ```

Doesn't solve the issue. Any other alternatives @dmhendricks? Thanks!

**Comment by louiechristie** [comment]
@anamwp @phpbits I had a related issue with the same error message #12. Here are instructions how I fixed it: https://github.com/zgordon/twentynineteen-gatsby-theme/issues/12#issuecomment-527946729
