### ISSUE TITLE
Initial thoughts on this super awesome thing :)

### ISSUE THREAD

**Issue by Shelob9** [zgordon/twentynineteen-gatsby-theme#7]
I wanted to share a few first impressions trying this and reading Muhammad's excellent post.

1) This is awesome. I got it setup with the example site with no problem.

2) Prefixing yarn workspace in commands is kind of annoying. I put commands in the root package.json to handle it for me

```
  "scripts" : {
    "develop" : "yarn workspace starter develop",
    "build" : "yarn workspace starter build",
    "start": "yarn workspace starter start"
  }
```
3) I wish I didn't have to edit the theme. Yes, that's my engrained WordPress instincts, but think about this.

- Use Lerna to publish the  /packages/gatsby-theme-twentynineteen and /packages/components packages to npm. I can put in a  PR for this.
- Make the templates directories extensible so I can change the partials out from my dare I say child theme.

4) For some reason, one page can not be created.

![Screen Shot 2019-03-29 at 3 06 50 PM](https://user-images.githubusercontent.com/1994311/55257744-3527f200-5237-11e9-893c-d9628654eb9e.png)

I think this means it can not import joshpress.net/josh - not sure why.

It seams like throwing a timeout error and moving on would be better. Maybe a log of what did not import.

**Comment by jasonbahl** [comment]
Great feedback @Shelob9! 

My favorite part is seeing joshpress.net is running WPGraphQL!! 😄

**Comment by m-muhsin** [comment]
Thanks for the sweet feedback @Shelob9!

1. That's great to hear the example site ran without any hiccups.

2. I have added those scripts to the root folder's package.json and pushed the changes. Thanks for that 👍

3. You're right. In fact we have plans to package it and publish it as a theme for other folks to import as an npm module. Feel free to join the efforts. Your inputs are very much valued.

4. Yeah, gets stuck for me too when I change the wordPressUrl to `https://joshpress.net` . Working on a fix now!

Cheers!
