### ISSUE TITLE
Date archives aren't created

### ISSUE THREAD

**Issue by lukecarbis** [zgordon/twentynineteen-gatsby-theme#9]
Following the steps from the readme, everything goes perfectly according to plan. I noticed that although Author, Category, and Tag archives exist, Date archives (e.g. `/2019/02`) don't exist, and the date links reference an unknown site (`http://localhost/mtwoblog.com/`).

![Screen Recording 2019-04-14 at 03 50 pm](https://user-images.githubusercontent.com/1097667/56088913-504c6000-5ecd-11e9-8236-ff65579b2745.gif)

**Comment by m-muhsin** [comment]
Thanks for reporting @lukecarbis 

Sorry about that, we will fix that shortly.

**Comment by m-muhsin** [comment]
The hard-coded date link to an unknown site is now gone.

**Comment by m-muhsin** [comment]
Closing as this is fixed!
